config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  resources :articles do
  	member do
      put 'close' => 'articles#close'
      put 'open' => 'articles#open'
    end
   end

  resources :activities do
    member do
      put 'close' => 'activities#close'
      put 'open' => 'activities#open'
    end
  end

  resources :users, except: [:new]
  resources :pictures, except: [:update,:edit]
  resources :films, except: [:show]

  get 'tags/:tag' => 'articles#index',as: :tag
  get 'columns' => 'articles#columns'
  get 'signup' => 'users#signup',:as => 'signup'
  get "login" => "users#login", :as => "login"
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"

end

app/models/article.rb
class Article < ActiveRecord::Base
	mount_uploader :thumb, ImageUploader
	belongs_to :user
	validates_length_of :summary, :maximum => 120 , :message => "摘要長度須小於120"
	validates_presence_of :title , :message => "請填寫標題"
	validates_presence_of :thumb , :message => "請上傳圖片"
	validates_presence_of :summary,:message => "請填寫摘要"
	acts_as_taggable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_login,only: %i[new]
  before_action :find_article, only: %i[show edit update destroy open close]

  def index
    @article  = Article.where({status: "0",created_at: 60.days.ago..Time.now }).order("created_at DESC").limit(6)
    @articleA = Article.where("status = 0 AND category LIKE ?","策展觀點").order('created_at DESC').limit(4)
    @articleB = Article.where("status = 0 AND category LIKE ?","十八分放大").order('created_at DESC').limit(4)
    @articleC = Article.where("status = 0 AND category LIKE ?","一百種臺南").order('created_at DESC').limit(4)
    @articleD = Article.where("status = 0 AND category LIKE ?","實踐者").order('created_at DESC').limit(4)
    @articleE = Article.where("status = 0 AND category LIKE ?","值得議題").order('created_at DESC').limit(4)
    @activities = Activity.where("status = 0").order('created_at DESC').limit(4)
    @hot = Article.where("status = 0").order("views DESC").first
	end

	def new
    @article = Article.new
  end

  def create
    @article= Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    prepare_meta_tags(title: @article.title,
                      description: @article.summary,
                      image: @article.thumb.url(:large),
                      keywords: @article.tag_list,
                      og: { image: @article.thumb.url(:large),
                            description: @article.summary})
    @morearticles = Article.where("status = 0").tagged_with(@article.tag_list).order("created_at DESC").limit(4)
    @article.views+=1
    @article.save
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to users_path }
      format.js
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def columns
    @article=Article.where("status = 0")
    @articleA = Article.where("status = 0 AND category LIKE ?","策展觀點").order('created_at DESC').first
    @articleB = Article.where("status = 0 AND category LIKE ?","十八分放大").order('created_at DESC').first
    @articleC = Article.where("status = 0 AND category LIKE ?","一百種臺南").order('created_at DESC').first
    @articleD = Article.where("status = 0 AND category LIKE ?","實踐者").order('created_at DESC').first
    @articleE = Article.where("status = 0 AND category LIKE ?","值得議題").order('created_at DESC').first
  end

  def open
    @article.status = 0
    flash[:success] = "關閉成功"
    @article.save
    redirect_to users_path
  end

  def close
    @article.status = 1
    flash[:success] = "開啟成功"
    @article.save
    redirect_to users_path
  end

  private
  	def find_article
      @article=Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title,:content,:summary,:category,:thumb,:status,:intro,:tag_list)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.erb
<div class="articles-part">
    <div class="articles-items">
        <% @article.each do |article| %>
            <div class="articles-item">
                <%= link_to image_tag(article.thumb.url(:square),:class => 'articles-item-img'), article %>
                <div class="articles-item-title">
                    <span class="h3"><%= link_to article.title , article %></span><br><br>
                    <span class="h4"><%= article.summary %></span>
                </div>
            </div>
        <% end %>
        <% if @article.count <= 6 %>
         <%= link_to '更多文章', columns_path , :id => 'more-button' ,:class => 'h3' %>
        <% end %>
    </div>
</div>

<script type="text/javascript">

  $(document).ready(function(){
    $('.articles-item').hover(function(){
      $('.articles-item-title',this).animate({
          opacity:1,
          bottom: "0",
      },500);
    },function(){
      $('.articles-item-title',this).animate({
          opacity:0,
          bottom: "-20px",
      },500);
    });
  })
</script>

<%# raw article.tag_list.map{ |t| link_to t , tag_path(t), :class => 'tags' }.join(" ") %>

app/views/articles/_category_article.erb
  <% @articleA.each do |article| %>
      <div class="a article">
          <div class="pic">
          <%=link_to image_tag( article.thumb_url , :class => 'pic-img'), article %>
        </div><p id="description" class="h3"><%= article.summary %></p>
      </div>
  <% end %>
  <% @articleB.each do |article| %>
      <div class="b article">
          <div class="pic">
          <%=link_to image_tag( article.thumb_url , :class => 'pic-img'), article %>
        </div><p id="description" class="h3"><%= article.summary %></p>
      </div>
  <% end %>
  <% @articleC.each do |article| %>
      <div class="c article">
          <div class="pic">
          <%=link_to image_tag( article.thumb_url , :class => 'pic-img'), article %>
        </div><p id="description" class="h3"><%= article.summary %></p>
      </div>
  <% end %>
  <% @articleD.each do |article| %>
      <div class="d article">
          <div class="pic">
          <%=link_to image_tag( article.thumb_url , :class => 'pic-img'), article %>
        </div><p id="description" class="h3"><%= article.summary %></p>
      </div>
  <% end %>
  <% @articleE.each do |article| %>
      <div class="e article">
          <div class="pic">
          <%=link_to image_tag( article.thumb_url , :class => 'pic-img'), article %>
        </div><p id="description" class="h3"><%= article.summary %></p>
      </div>
  <% end %>
  <% @activities.each do |activity| %>
      <div class="f article">
          <div class="pic">
          <%=link_to image_tag( activity.thumb_url , :class => 'pic-img'), activity %>
        </div><p id="description" class="h3"><%= activity.summary %></p>
      </div>
  <% end %>

app/views/articles/_columns_article.html.erb
<% if @articleA %>
  <div class="columns-article a">
    <%= link_to image_tag( @articleA.thumb.url(:square) , :class => 'columns-article-img'), @articleA %>
    <div class="columns-article-content">
      <p class="h1"><%=link_to @articleA.title,@articleA %></p>
      <hr style="border-color:black;">
      <p class="h3"><%= @articleA.summary %></p>
    </div>
  </div>
<% end %>
<% if @articleB %>
  <div class="columns-article b">
    <%= link_to image_tag( @articleB.thumb.url(:square) , :class => 'columns-article-img'), @articleB %>
    <div class="columns-article-content">
      <p class="h1"><%=link_to @articleB.title,@articleB %></p>
      <hr style="border-color:black;">
      <p class="h3"><%= @articleB.summary %></p>
    </div>
  </div>
<% end %>
<% if @articleC %>
  <div class="columns-article c">
    <%= link_to image_tag( @articleC.thumb.url(:square) , :class => 'columns-article-img'), @articleC %>
    <div class="columns-article-content">
      <p class="h1"><%=link_to @articleC.title ,@articleC %></p>
      <hr style="border-color:black;">
      <p class="h3"><%= @articleC.summary %></p>
    </div>
  </div>
<% end %>
<% if @articleD %>
  <div class="columns-article d">
    <%= link_to image_tag( @articleD.thumb.url(:square) , :class => 'columns-article-img'), @articleD %>
    <div class="columns-article-content">
      <p class="h1"><%=link_to @articleD.title,@articleD %></p>
      <hr style="border-color:black;">
      <p class="h3"><%= @articleD.summary %></p>
    </div>
  </div>
<% end %>
<% if @articleE %>
  <div class="columns-article e">
    <%= link_to image_tag( @articleE.thumb.url(:square) , :class => 'columns-article-img'), @articleE %>
    <div class="columns-article-content">
      <p class="h1"><%=link_to @articleE.title,@articleE %></p>
      <hr style="border-color:black;">
      <p class="h3"><%= @articleE.summary %></p>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<% if @article.errors.count > 0 %>
	<p class="alert alert-warning formalert">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<% @article.errors.each do |attr,msg|  %>
			<%= msg %><br>
		<% end %>
	</p>
<% end %>

<%= form_for @article, :html => {:class => "form"} do |f| %>
	<div class="form-group">
		<%= f.label :title, '標題: ' %>
		<%= f.text_field :title , :class =>"form-control" %><br><br>
	</div>
	<div class="form-group">
		<%= f.label :category, '分類: ' %>
		<%= f.select :category, %w[策展觀點 十八分放大 一百種臺南 實踐者 值得議題] , :class =>"form-control" %><br><br>
	</div>
	<div class="form-group">
		<%= f.label :tag_list, '標籤(請用逗點分隔): ' %>
		<%= f.text_field :tag_list, :class =>"form-control" %><br><br>
	</div>
	<div class="form-group">
		<div id="preview"></div><br>
		<%= f.label :thumb, '縮圖: ' %>
		<%= f.file_field :thumb , :class =>"form-control",:id =>'pictureupload' %><br><br>
		<%= f.hidden_field(:thumb_cache) %>
	</div>
	<div class="form-group">
		<%= f.label :summary, '摘要: ' %>
		<%= f.text_area :summary, :class =>"form-control" ,:id => 'textarea'%><br>
		<p>目前 <span id="count">0</span> 字</p><br><br>
	</div>
	<div class="form-group">
		<%= f.label :intro, '引言: ' %>
		<%= f.text_area :intro, :class =>"form-control" %><br><br>
	</div>
	<div class="form-group">
		<%= f.text_area :content, class: 'tinymce' %><br>
		<%= f.submit '建立', :class =>"btn btn-default" %>
		<%= link_to '返回', :back , :class =>"btn btn-default" %>
	</div>
<% end %>


<script>

	$(document).ready(function () {
    	tinyMCE.remove();
    	tinyMCE.init({
			selector: "textarea.tinymce",
			toolbar: ["fullscreen | undo redo | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | table | link unlink image media | emoticons | hr nonbreaking","formatselect | fontsizeselect | bold italic underline strikethrough | subscript superscript | forecolor backcolor | removeformat | preview"],
			plugins: "advlist,autolink,lists,link,image,charmap,preview,hr,anchor,searchreplace,visualblocks,visualchars,code,fullscreen,insertdatetime,media,nonbreaking,table,contextmenu,textcolor,colorpicker",
			menubar: false
		});

		$('#pictureupload').on('change', function(event) {
	    	var files = event.target.files;
	    	var image = files[0]
	    	var reader = new FileReader();
		    reader.onload = function(file){
		      var img = new Image();
		      img.src = file.target.result;
		      $('#preview').html(img);
		    }
	    	reader.readAsDataURL(image);
	  	});

			var area = document.getElementById('textarea');
			var count = document.getElementById('count');
			Countable.live(area, function (counter) {
				if(counter['all']>150){
					count.style.color = 'red';
				}
				else {
					count.style.color = 'black';
				}
  			count.innerHTML=counter['all'];
			})
	});
</script>

app/views/articles/columns.html.erb
<div class="container-fluid" style="background:rgb(244,244,244);">
  <div class="row">
    <div class="col-md-7 col-md-offset-1">
      <%= render 'columns_article' %>
    </div>
    <div class="col-md-2 col-md-offset-1">
      <ul class="columns-btns">
        <li id="A">策展觀點</li>
        <li id="B">十八分放大</li>
        <li id="C">一百種臺南</li>
        <li id="D">實踐者</li>
        <li id="E">值得議題</li>
      </ul>
    </div>
  </div>
</div>
<%= render 'articles' %>

<script type="text/javascript">
  $(document).ready(function () {
    $(".b").hide();
    $(".c").hide();
    $(".d").hide();
    $(".e").hide();
    $(".f").hide();
    var prev = ".a";
    $("#A").mouseenter(function () {
      if (prev != ".a") {
        $(prev).hide();
        $(".a").show();
        prev = ".a";
      }
    });
    $("#B").mouseenter(function () {
      if (prev != ".b") {
        $(prev).hide();
        $(".b").show();
        prev = ".b";
      }
    });
    $("#C").mouseenter(function () {
      if (prev != ".c") {
        $(prev).hide();
        $(".c").show();
        prev = ".c";
      }
    });
    $("#D").mouseenter(function () {
      if (prev != ".d") {
        $(prev).hide();
        $(".d").show();
        prev = ".d";
      }
    });
    $("#E").mouseenter(function () {
      if (prev != ".e") {
        $(prev).hide();
        $(".e").show();
        prev = ".e";
      }
    });
    $("#F").mouseenter(function () {
      if (prev != ".f") {
        $(prev).hide();
        $(".f").show();
        prev = ".f";
      }
    });
  });
</script>

app/views/articles/destroy.js.erb
$('#<%= dom_id(@article) %>').fadeOut();

app/views/articles/edit.html.erb
<div class="container">
	<div class="row">
		<h1 class="text-center h1">編輯文章</h1>
		<div class="col-md-10 col-md-offset-1">
			<%= render 'form' %>
			<div style="display:block;height:300px;"></div>
		</div>
	</div>
</div>

app/views/articles/index.html.erb
<div class="news">
  <div class="news-row">
    <div class="news-row-item">
      <ul class="topic">
        <li>
          <a href="#" id="A" class="h1">策展觀點</a>
        </li><li>
          <a href="#" id="B" class="h1">十八分放大</a>
        </li><li>
          <a href="#" id="C" class="h1">一百種臺南</a>
        </li><li>
          <a href="#" id="D" class="h1">實踐者</a>
        </li><li>
          <a href="#" id="E" class="h1">值得議題</a>
        </li><li>
          <a href="#" id="F" class="h1">活動資訊</a>
        </li>
      </ul>
    </div><div class="news-row-item" style="vertical-align:top;">
      <div class="intro a">a</div>
      <div class="intro b">b</div>
      <div class="intro c">c</div>
      <div class="intro d">d</div>
      <div class="intro e">e</div>
      <div class="intro f">f</div>
    </div>
  </div>
  <div class="news-row">
    <div class="news-row-item">
      <div id="hotarticle">
        <% if @hot %>
        <p id="hotarticle-title" class="h1">熱門文章</p>
        <%=link_to image_tag(@hot.thumb.url(:large) , :class => 'hotarticle-img'), @hot %>
        <p id="hotarticle-title" class="h1"><%= @hot.title %></p>
        <p id="hotarticle-description" class="h3"><%= @hot.summary %></p>
        <% end %>
      </div>
    </div><div class="news-row-item" style="vertical-align:top;">
      <%= render 'category_article' %>
    </div>
  </div>
</div>
<%= render 'articles' %>
<script type="text/javascript">
  $(document).ready(function () {
    $(".b").hide();
    $(".c").hide();
    $(".d").hide();
    $(".e").hide();
    $(".f").hide();
    var prev = ".a";
    $("#A").mouseenter(function () {
      if (prev != ".a") {
        $(prev).hide();
        $(".a").show();
        prev = ".a";
      }
    });
    $("#B").mouseenter(function () {
      if (prev != ".b") {
        $(prev).hide();
        $(".b").show();
        prev = ".b";
      }
    });
    $("#C").mouseenter(function () {
      if (prev != ".c") {
        $(prev).hide();
        $(".c").show();
        prev = ".c";
      }
    });
    $("#D").mouseenter(function () {
      if (prev != ".d") {
        $(prev).hide();
        $(".d").show();
        prev = ".d";
      }
    });
    $("#E").mouseenter(function () {
      if (prev != ".e") {
        $(prev).hide();
        $(".e").show();
        prev = ".e";
      }
    });
    $("#F").mouseenter(function () {
      if (prev != ".f") {
        $(prev).hide();
        $(".f").show();
        prev = ".f";
      }
    });
  });
</script>

app/views/articles/new.html.erb
<div class="container">
	<div class="row">
		<h1 class="text-center h1">發表文章</h1>
		<div class="col-md-8 col-md-offset-2">
			<%= render 'form' %>
			<div class="block" ></div>
		</div>
	</div>
</div>

app/views/articles/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<% if current_user %>
			<div class="article-ctrl">
				<div class="btn-group" role="group" aria-label="...">
					<%= link_to '編輯',edit_article_path(@article), :class => "btn btn-default" %>
					<%= link_to '刪除',article_path(@article),method: :delete,data: { confirm: "確定刪除嗎?" }, :class =>"btn btn-default" %>
				</div>
			</div>
			<% end %>
			<div class="article-meta">
				<p class="article-title"><%= @article.title %></p><br><br>
				<p class="article-author-name h3" style="display:none;">作者 | <%= @article.user.name %></p>
			</div>
			<% if @article.intro != '' %>
				<div class="article-intro"><%= @article.intro %></div>
			<% end %>
			<div class="article-content"><%=raw @article.content %></div>
			<div class="article-author" style="display:none;">
				<div class="article-author-avatar"><%= image_tag @article.user.avatar_url(:thumb) %></div>
				<div class="article-author-profile">
					<p class="h2">作者 | <%= @article.user.name %></p><br>
					<p class="h2"><%= @article.user.profile %></p>
				</div>
			</div>
			<div class="more-articles">
				<h1 class="h1" style="padding-bottom:20px;padding-left:10px;">延伸閱讀</h1>
				<% @morearticles.each  do |morearticle| %>
					<div class="more-article-item">
						<%= link_to image_tag(morearticle.thumb.url(:square) , :class => 'more-article-item-img'), morearticle %>
						<%= link_to morearticle.title , morearticle , :class => 'more-article-item-title h3'%>
					</div>
				<% end %>
			</div>
			<div class="article-comment">
				<div id="disqus_thread"></div>
					<script>
					(function() {
					var d = document, s = d.createElement('script');

					s.src = '//tedxtainan2016.disqus.com/embed.js';

					s.setAttribute('data-timestamp', +new Date());
					(d.head || d.body).appendChild(s);
					})();
					</script>
			</div>
		</div>
	</div>
</div>