config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  resources :articles do
  	member do
      put 'close' => 'articles#close'
      put 'open' => 'articles#open'
    end
   end

  resources :activities do
    member do
      put 'close' => 'activities#close'
      put 'open' => 'activities#open'
    end
  end

  resources :users, except: [:new]
  resources :pictures, except: [:update,:edit]
  resources :films, except: [:show]

  get 'tags/:tag' => 'articles#index',as: :tag
  get 'columns' => 'articles#columns'
  get 'signup' => 'users#signup',:as => 'signup'
  get "login" => "users#login", :as => "login"
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :articles, dependent: :destroy
	has_many :activities, dependent: :destroy

	validates_length_of :password, :minimum => 8 , :message => "密碼長度須大於8", on: :create
	validates_uniqueness_of :email, :message => "信箱已被使用", on: :create
	validates_format_of :email, :with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i, :message => "請輸入信箱"
	validates_presence_of :name , :message => "請填寫名稱"
	validates_presence_of :profile,:message => "請填寫自我介紹"
	mount_uploader :avatar, AvatarUploader
	attr_accessor :crop_x, :crop_y,:crop_w,:crop_h
	after_update :crop_avatar

	def crop_avatar
		avatar.recreate_versions! if crop_x.present?
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :check_login,only: %i[index edit]
	  def index
      @article = Article.all
      @activities = Activity.all
    end

    def signup
    	@user = User.new
  	end

   	def create
    	@user=User.new(user_params)
    	if @user.save
        if params[:user][:avatar].present?
          render :crop
        else
          flash[:success] = "註冊成功"
          redirect_to root_path
        end
      else
        flash[:danger] = "註冊失敗"
        render 'signup'
      end
  	end

  	def create_login_session
    	@user =User.find_by_email(params[:email])
    	if @user && @user.authenticate(params[:password])
      		session[:user_id]= @user.id
          flash[:success] = "登入成功"
      		redirect_to root_path
    	else
          if @user
            flash[:danger] = "登入失敗,密碼錯誤"
          else
            flash[:danger] = "登入失敗,信箱或密碼錯誤"
          end
      		redirect_to :login
    	end
  	end


  	def logout
    	session[:user_id]=nil
      flash[:danger] = "已將您登出"
    	redirect_to root_path
  	end


    def edit
      @user = current_user
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        if params[:user][:avatar].present?
          render :crop
        else
          flash[:success] = "更新成功"
          redirect_to user_path(@user)
        end
      else
        flash[:danger] = "更新失敗"
        render 'edit'
      end
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      session[:user_id]=nil
      flash[:success] = "刪除帳號成功"
      redirect_to root_path
    end

    def show
      @user = User.find(params[:id])
    end

  	private
   		def user_params
     		params.require(:user).permit(:crop_x, :crop_y, :crop_w, :crop_h,:avatar,:name,:email,:profile,:password)
   		end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/crop.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<h1 class="text-center h1">裁切圖片</h1>
			<div id="previewbox">
				<%= image_tag @user.avatar.url(:large), :id=> "preview" %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<%= image_tag @user.avatar_url(:large), :id => 'cropbox' %>
			<%= form_for @user do |f| %>
				<div class="action">
					<% %w[x y w h].each do |attr| %>
						<%= f.hidden_field "crop_#{attr}" %><br>
					<% end %>
					<%= f.submit '裁切' , :class => 'btn btn-default', :id =>'crop-btn' %>
				</div>
			<% end %>
			<div class="block"></div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1 class="text-center h1">個人資料</h1>
			<%= image_tag(@user.avatar.url(:thumb),:class => "avatar")%>
			<%= form_for @user, :html => {:class => "form"} do |f| %>
			  <%= f.label :avatar, '大頭照' %>
			  <%= f.file_field :avatar,:class =>"form-control" %><br>
			  <%= f.label :name, '用戶名' %>
			  <%= f.text_field :name, :class =>"form-control"  %><br>
			  <%= f.label :email, 'Email' %>
			  <%= f.text_field :email, :class =>"form-control"  %><br>
			  <%= f.label :profile, '個人簡介' %>
			  <%= f.text_area :profile, :class =>"form-control"  %><br>
			  <%= f.submit '更新', :class =>"btn btn-default" %>
			<% end %>
			<div class="block" ></div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="h1 text-center">文章管理</h1><br>
			<table class="table table-bordered text-center">
				<tr>
					<th>標題</th>
					<th>分類</th>
					<th>瀏覽量</th>
					<th>作者</th>
					<th>發表日期</th>
					<th>狀態</th>
					<th>管理</th>
				</tr>
			<% @article.each do |article| %>
				<tr id="<%= dom_id article %>">
					<td><%= link_to article.title,article %></td>
					<td><%= article.category %></td>
					<td><%= article.views %></td>
					<td><%= link_to article.user.name,article.user %></td>
					<td><%= article.created_at.strftime("%Y/%m/%d") %></td>
					<td>
						<% if article.status == 0 %>
							開放
						<% else %>
							關閉
						<% end %>
					</td>
					<td>
						<%= link_to '刪除', article_path(article),:class => "btn btn-default", method: :delete,remote: true,data: { confirm: "確定刪除嗎?" } %>
                        <%= link_to '編輯', edit_article_path(article),:class => "btn btn-default" %>
                        <% if article.status == 0 %>
                        	<%= link_to '關閉', close_article_path(article),method: :put, :class => "btn btn-default" %>
                        <% else %>
							<%= link_to '開啟', open_article_path(article),method: :put,:class => "btn btn-default" %>
                        <% end %>
                    </td>
				</tr>
			<% end %>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<h1 class="h1 text-center">活動管理</h1><br>
			<table class="table table-bordered text-center">
				<tr>
					<th>標題</th>
					<th>分類</th>
					<th>瀏覽量</th>
					<th>發表日期</th>
					<th>狀態</th>
					<th>管理</th>
				</tr>
			<% @activities.each do |activity| %>
				<tr id="<%= dom_id activity %>">
					<td><%= link_to activity.title,activity %></td>
					<td><%= activity.category %></td>
					<td><%= activity.views %></td>
					<td><%= activity.date.strftime("%Y/%m/%d") %></td>
					<td>
						<% if activity.status == 0 %>
							開放
						<% else %>
							關閉
						<% end %>
					</td>
					<td>
						<%= link_to '刪除', activity_path(activity),:class => "btn btn-default", method: :delete,remote: true,data: { confirm: "確定刪除嗎?" } %>
            <%= link_to '編輯', edit_activity_path(activity),:class => "btn btn-default" %>
            <% if activity.status == 0 %>
            	<%= link_to '關閉', close_activity_path(activity),method: :put, :class => "btn btn-default" %>
            <% else %>
							<%= link_to '開啟', open_activity_path(activity),method: :put,:class => "btn btn-default" %>
            <% end %>
         </td>
				</tr>
			<% end %>
			</table>
		</div>
	</div>
</div>

app/views/users/login.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1 class="text-center h1">登入</h1>
			<%= form_tag "create_login_session" do %>
			    <%= label_tag "信箱" %>
			    <%= text_field_tag :email ,params[:email], :class =>"form-control"  %><br>
			    <%= label_tag "密碼" %>
			    <%= password_field_tag :password, params[:password], :class =>"form-control"  %><br>
			    <%= submit_tag "登入", :class =>"btn btn-default"  %>
			<% end %>
		</div>
	</div>
</div>
<div class="block"></div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= image_tag @user.avatar.url(:thumb) , :class => "avatar" %>
			<table class="table">
				<tr>
					<th>用戶名</th>
					<td><%= @user.name %></td>
				</tr>
				<tr>
					<th>Email</th>
					<td><%= @user.email %></td>
				</tr>
				<tr>
					<th>個人介紹</th>
					<td><%= @user.profile %></td>
				</tr>
			</table>
			<% if current_user %>
				<% if current_user.id == @user.id %>
				<div class="text-center">
					<%= link_to '編輯個人資料' , edit_user_path , :class => 'btn btn-default' %>
					<%= link_to '刪除帳號' , user_path(current_user) , :class => 'btn btn-default', method: :delete, data: { confirm: "確定刪除嗎?" } %>
				</div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>
<div class="block"></div>

app/views/users/signup.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1 class="text-center h1">註冊</h1>
			<% if @user.errors.count > 0 %>
				<p class="alert alert-warning formalert">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<% @user.errors.each do |attr,msg|  %>
		 				<%= msg %><br>
					<% end %>
				</p>
			<% end %>
			<%= form_for @user, :html => {:class => "form"} do |f| %>
				<div class="form-group">
			  		<%= f.label :avatar, '大頭照' %>
			  		<%= f.file_field :avatar,:class =>"form-control" %><br>
				</div>
			  	<div class="form-group">
			  		<%= f.label :name, '用戶名' %>
			  		<%= f.text_field :name, :class =>"form-control" %><br>
				</div>
			  	<div class="form-group">
			  		<%= f.label :email, 'Email' %>
			  		<%= f.text_field :email, :class =>"form-control" %><br>
			  	</div>
			  	<div class="form-group">
			  		<%= f.label :password, '密碼' %>
			  		<%= f.password_field :password, :class =>"form-control"  %><br>
			  	</div>
			  	<div class="form-group">
			  		<%= f.label :password_confirmation, '確認密碼' %>
			  		<%= f.password_field :password_confirmation, :class =>"form-control"  %><br>
			  	</div>
			  	<div class="form-group">
			  		<%= f.label :profile, '個人簡介' %>
			  		<%= f.text_area :profile, :class =>"form-control"  %><br>
			  	</div>
			  	<%= f.submit '註冊', :class =>"btn btn-default" %>
			<% end %>
		</div>
	</div>
</div>
<div class="block"></div>