config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  resources :articles do
  	member do
      put 'close' => 'articles#close'
      put 'open' => 'articles#open'
    end
   end

  resources :activities do
    member do
      put 'close' => 'activities#close'
      put 'open' => 'activities#open'
    end
  end

  resources :users, except: [:new]
  resources :pictures, except: [:update,:edit]
  resources :films, except: [:show]

  get 'tags/:tag' => 'articles#index',as: :tag
  get 'columns' => 'articles#columns'
  get 'signup' => 'users#signup',:as => 'signup'
  get "login" => "users#login", :as => "login"
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :check_login,only: %i[new]
  before_action :find_picture, only: %i[show destroy]

  def index
    @picture = Picture.all
  end

  def new
    @picture = Picture.new
  end


  def create
    @picture= Picture.new(picture_params)
    if @picture.save
      redirect_to @picture
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  private
  	def find_picture
      @picture=Picture.find(params[:id])
    end

    def picture_params
      params.require(:picture).permit(:image,:name)
    end
end

app/helpers/picture_helper.rb
module PictureHelper
end

app/views/pictures/destroy.js.erb
$('#<%= dom_id(@picture) %>').fadeOut();

app/views/pictures/index.html.erb
<div class="container">
	<div class="row">
		<% @picture.each do |p| %>
			<div class="col-md-3 text-center" id="<%= dom_id p %>" >
				<%= image_tag(p.image_url, :class => 'picture') %>
				<p><%= p.name %></p>
				<div class="btn-group" role="group" style="margin:10px auto;">
					<%= link_to '查看', p,:class => "btn btn-default" %>
					<%= link_to '刪除', picture_path(p),:class => "btn btn-default", method: :delete,remote: true, data: {confirm: "確定刪除嗎?" } %>
				</div>
				<p><%= text_field_tag 'url', p.image_url , :class =>'form-control' %></p>
			</div>
		<% end %>
	</div>
</div>

app/views/pictures/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1 class="h1 text-center">上傳圖片</h1>
			<%= form_for @picture, :html => {:class => "form"}  do |f| %>
				<%= f.label :name, '名稱: ' %>
				<%= f.text_field :name , :class =>"form-control" %><br><br>
				<div id="preview"></div>
			  	<%= f.file_field :image, :class => "form-control",:id => "pictureupload" %><br>
			  	<%= f.submit "上傳", :class => "btn btn-default" %>
			<% end %>
			<div class="block"></div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(function() {
	  $('#pictureupload').on('change', function(event) {
	    var files = event.target.files;
	    var image = files[0]
	    var reader = new FileReader();
	    reader.onload = function(file) {
	      var img = new Image();
	      img.src = file.target.result;
	      $('#preview').html(img);
	    }
	    reader.readAsDataURL(image);
	  });
	});
</script>

app/views/pictures/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= image_tag(@picture.image_url , :class => 'picture') %>
		</div>
	</div>
</div>