config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  resources :articles do
  	member do
      put 'close' => 'articles#close'
      put 'open' => 'articles#open'
    end
   end

  resources :activities do
    member do
      put 'close' => 'activities#close'
      put 'open' => 'activities#open'
    end
  end

  resources :users, except: [:new]
  resources :pictures, except: [:update,:edit]
  resources :films, except: [:show]

  get 'tags/:tag' => 'articles#index',as: :tag
  get 'columns' => 'articles#columns'
  get 'signup' => 'users#signup',:as => 'signup'
  get "login" => "users#login", :as => "login"
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="col-md-6">
    <%= image_tag 'menu/tedlogo.png', :id => 'footerlogo'%>
  </div>
  <div class="col-md-6">
    <div class="footer-icons">
      <a href="https://www.facebook.com/TEDxTainan" target="_blank"><i class="fa fa-facebook" id="footer-fb"></i></a>
      <a href="https://www.instagram.com/tedxtainan/" target="_blank"><i class="fa fa-instagram"></i></a>
    </div>
  </div>
</div>

app/views/layouts/_menu.html.erb
<div class="navbar" id="mobile-menu">
  <div class="container-fluid" style="padding-top:0px;padding-bottom:0px;">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('menu/tedlogo.png'),root_path, :class => "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%=link_to '專欄文章', columns_path %></li>
        <li>
          <%= link_to '活動資訊', activities_path %>
        </li>
        <li>
          <%= link_to '講者影片', films_path %>
        </li>
        <li>
          <a href="#">關於我們</a>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="nav-menu" id="desktop-menu">
  <div class="nav-logo-category">
    <div class="nav-logo">
      <%= link_to image_tag('menu/tedlogo.png'),root_path %>
      <div class="nav-category">
        <ul class="menu-items">
          <li class="menu-item">
            <%=link_to '專欄文章', columns_path %>
          </li>
          <li class="menu-item">
            <%= link_to '活動資訊', activities_path %>
          </li>
          <li class="menu-item">
            <%= link_to '講者影片', films_path %>
          </li>
          <li class="menu-item">
            <a href="">
              關於我們
            </a>
          </li>
        </ul>
      </div>
      <div class="right">
        <a href="https://www.facebook.com/TEDxTainan" target="_blank"><i class="fa fa-facebook" ></i></a>
        <a href="https://www.instagram.com/tedxtainan/" target="_blank"><i class="fa fa-instagram"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_usermenu.html.erb
<div class="navbar-default">
    <div class="container-fluid" style="padding-top:0;padding-bottom:0px;">
        <div>
            <%= link_to image_tag(current_user.avatar.url(:thumb),:id =>'menu-avatar'), user_path(current_user) %>
            <ul class="nav navbar-nav">
            	<li><a>歡迎 <%= current_user.name %></a></li>
                <li><%= link_to '個人資料', user_path(current_user) %></li>
                <li><%= link_to '文章/活動管理', users_path %></li>
                <li><%= link_to '發表文章', new_article_path %></li>
                <li><%= link_to '發表活動', new_activity_path %></li>
                <li><%= link_to '發表影片', new_film_path %></li>
                <li><%= link_to '上傳圖片', new_picture_path %></li>
                <li><%= link_to '圖片庫', pictures_path %></li>
                <li><%= link_to "登出",logout_path,method: :delete %></li>
            </ul>
        </div>
    </div>
</div>